### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by SmartVive** [azhon/AppUpdate#100]
DownloadManager的dialog和ButtonClickListener会造成内存泄漏，希望能在release方法里设置为null

**Comment by SmartVive** [comment]
似乎是DownloadService中downloadManager释放时没有设置为null导致的，所以直接在releaseResources方法把downloadManagers设为null也能解决这个问题

**Comment by SmartVive** [comment]
最终发现其实是HttpDownloadManager的listener持有DownloadService导致的，所以前面说的都不用修改，只需要在DownloadService.releaseResources()中把HttpDownloadManager的listener设为null就能解决了。

**Comment by azhon** [comment]
那就在BaseHttpDownloadManager中增加个release()方法了，然后将HttpDownloadManager = null

**Comment by SmartVive** [comment]
对的，下载完成调用BaseHttpDownloadManager的relase()就行

**Comment by azhon** [comment]
ok

**Comment by azhon** [comment]
已在3.0.2版本上加上了
