### ISSUE TITLE
使用了这个包后上架GooglePlay失败，想问下如何彻底移除

### ISSUE THREAD

**Issue by heshiweij** [azhon/AppUpdate#106]
**Bug标题**
使用了这个包后上架GooglePlay失败，请问如何彻底的移除

After using this package, GooglePlay failed to be listed. How can I remove it completely?

**软件版本信息**
 - Android Studio：4.1
 - AppUpdate：3.0.3

第一次上架，GooglePlay 拒绝了，理由是

The first time it was put on the shelves, GooglePlay rejected it on the grounds that

```
Your app contains content that doesn’t comply with the Device and Network Abuse policy. We found your app is using a non-compliant version of Azhon AppUpdate SDK which contains code to download or install applications from unknown sources outside of Google Play.
```

当我们在 build.grade 移除这个包的依赖，甚至全局搜了 "Azhon" 这个关键字，确定没有使用了以后重新打包，重新上传，依然以同样的理由被拒绝。

When we removed the dependency of this package in build.grade, and even searched the keyword "Azhon" globally, we repackaged and re-uploaded it after confirming that it was not used, but it was still rejected for the same reason.

请问我该如何彻底移除这个 Azhon 这个依赖，是哪里漏掉了吗？

How can I completely remove this Azhon dependency? Is there something missing?

**Comment by azhon** [comment]
是不是你自己的项目配置了 安装apk的权限。
你把库都移除依赖了，那就和我没关系了

**Comment by 123yangu** [comment]
我也遇到了同样的问题@heshiweij你有解决这个问题吗，@azhon我本地所有的库确定都没有设置REQUEST_INSTALL_PACKAGES权限

**Comment by jack2antom** [comment]
googlePlay现在对申请了install权限的apk都做了ban处理。我也遇到了这个问题，目前在考虑用谷歌Play自己的升级框架.creater有什么好的想法吗
