### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by facaige888** [azhon/AppUpdate#109]
**Bug标题**
清楚简明的描述你遇到的问题

**AppUpdate参数设置**
截图`DownloadManager`配置

**复现步骤**

**错误Logcat日志截图**
日志截图

**软件版本信息**
 - Android Studio：
 - AppUpdate：
 - 设备品牌：
 - 设备型号：
 - 设备系统版本：

**额外有用的信息**
补充额外有用的信息
获取文件content-lench为-1

**Comment by azhon** [comment]
这个和你的下载地址有关系
