### ISSUE TITLE
通知栏提示下载失败

### ISSUE THREAD

**Issue by hbwangzhen** [azhon/AppUpdate#11]
我直接下载的时候失败，在HttpDownloadManager 的类中的  getContentLength方法中con得到的是null，链接放到浏览器中是可以下载的

**Comment by hbwangzhen** [comment]
不知道是不是下载的url有什么限制？

**Comment by azhon** [comment]
把你的下载地址贴一下，我看下。

**Comment by wangcc0909** [comment]
这个问题我这也遇到过   我用的是该demo中的apk的url做下载地址 ,请问这个问题该怎么解决  使用的手机是小米note3

**Comment by azhon** [comment]
你看下Logcat具体的报错，或者debug一下

**Comment by azhon** [comment]
问题已解决 依赖最新版本v1.5.5即可
`
HttpURLConnection设置为gzip方式获取
con.setRequestProperty("Accept-Encoding", "identity");
`
