### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Julieforgithub** [azhon/AppUpdate#110]
**Bug标题**
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

**AppUpdate参数设置**
截图`DownloadManager`配置
implementation 'com.github.azhon:AppUpdate:3.0.5'

**复现步骤**
Android 12

**错误**
日志截图
![image](https://user-images.githubusercontent.com/56393895/145165056-6ae7bc36-7064-4481-b0db-f33575c7aa2f.png)

**软件版本信息**
 - Android Studio：Android Studio Arctic Fox | 2020.3.1 Patch 3
Build #AI-203.7717.56.2031.7784292, built on October 1, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true, debugger.watches.in.variables=false
Non-Bundled Plugins: wu.seal.tool.jsontokotlin, org.jetbrains.kotlin
 - AppUpdate：implementation 'com.github.azhon:AppUpdate:3.0.5'
 - 设备品牌：Mac
 - 设备型号：
 - 设备系统版本：

**额外有用的信息**
补充额外有用的信息

**Comment by lihenggui** [comment]
It will cause crashes if the app targets Android 31+.

Reference: https://developer.android.com/guide/components/intents-filters#DeclareMutabilityPendingIntent

As you can see from the source, this line doesn't add such information about mutability. https://github.com/azhon/AppUpdate/blob/main/appupdateX/src/main/java/com/azhon/appupdate/utils/NotificationUtil.java#L146

**Comment by azhon** [comment]
I have changed the flag of `PendingIntent` to `FLAG_IMMUTABLE`, can you update the code and test it.

**Comment by Julieforgithub** [comment]
请问可以发布一个测试版本吗？我没有直接集成你的代码，所以没有办法进行修改测试。

**Comment by azhon** [comment]
发不了测试本，你直接下载github的代码跑你手机试试

**Comment by Julieforgithub** [comment]
我在本地测试通过了，不会crash了，谢谢。

**Comment by Julieforgithub** [comment]
请问什么时候会发新版本呢？

**Comment by azhon** [comment]
发布了
