### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by kyle-y** [azhon/AppUpdate#112]
**Bug标题**
通知栏更新问题

**复现步骤**
点击立即更新，通知栏出现下载进度条，主动断网，通知栏显示为下载错误。但有较大概率通知栏没有更新，还是显示进度条且无法取消

**额外有用的信息**
* 从打印日志来看，断网时AppUpdate.DownloadService: error: javax.net.ssl.SSLException: Read error: ssl=0xe8852ec8: I/O error during system call, Software caused connection abort
触发了error, 通知应该是发出去了，但是系统没有响应。
* 另外小米手机会将“下载错误”的通知显示在 不重要通知分类里，也会导致进度条常驻
* 最新版3.0.6同样存在该问题

**Comment by kyle-y** [comment]
我用库中的demo测试没有出现这个问题，但是我的项目集成本库后，出现这个问题的概率挺高，特别是用流量进行下载的时候，暂不知是什么原因

**Comment by azhon** [comment]
你参照下`showDoneNotification`代码，发送错误通知时，先取消在，发送看看
<img width="933" alt="image" src="https://user-images.githubusercontent.com/20559556/146857079-c423e7f9-5615-48fb-99c5-bfd9f14e22c4.png">

**Comment by kyle-y** [comment]
> 你参照下`showDoneNotification`代码，发送错误通知时，先取消在，发送看看 <img alt="image" width="933" src="https://user-images.githubusercontent.com/20559556/146857079-c423e7f9-5615-48fb-99c5-bfd9f14e22c4.png">

加入了这个cancel后，出现概率性通知栏被取消，但没有出现新的“下载错误”通知栏的情况。另外试了下让NotificationUtil.showErrorNotification这个方法延迟200ms调用，测试多次，似乎能解决这个问题。

**Comment by azhon** [comment]
> 
那可能就是通知发送频繁导致的吧
