### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by ZSFeng** [azhon/AppUpdate#116]
**Bug标题**
出现内存泄漏

**复现步骤**
在Home页面弹出更新，点击升级，提示在后台下载，然后切换到Login页面，关闭Home页面出现内存泄漏

**错误Logcat日志截图**
![Screenshot_20220120-114424](https://user-images.githubusercontent.com/24423966/150275213-100b082b-23e3-4121-82de-e1aa38a13488.png)

**Comment by ZSFeng** [comment]
就是还在下载的过程中，关闭了依附的Activity，会出现内存泄漏，我现在的做法就在onDestory()里进行释放
   if (downloadManager != null) {
            downloadManager.cancel();
            if (downloadManager.getConfiguration().getHttpManager() != null) {
                downloadManager.getConfiguration().getHttpManager().release();
            }
            downloadManager.release();
            stopService(new Intent(this, DownloadService.class));
        }

**Comment by azhon** [comment]
等我有时间看下怎么改😄

**Comment by azhon** [comment]
@ZSFeng 进下qq群：828385813，沟通一下

**Comment by azhon** [comment]
已在V3.0.7版本修复
