### ISSUE TITLE
后台捕捉到的用户客户端 App Crash

### ISSUE THREAD

**Issue by realskyrin** [azhon/AppUpdate#117]
**App Crash**
后台捕捉到的用户客户端 Crash 日志，未能成功在本地复现

**AppUpdate参数设置**
<img width="768" alt="image" src="https://user-images.githubusercontent.com/16552732/163763873-42f7cc6c-1107-4f59-8010-2c5fb3132ca4.png">

**复现步骤**

**错误Logcat日志截图**
<img width="772" alt="image" src="https://user-images.githubusercontent.com/16552732/163765215-54b67f30-f3d2-487b-beda-5d5a3a354cbf.png">

**软件版本信息**
 - Android Studio：
 - AppUpdate：v4.0.0
 - 设备品牌：Huawei
 - 设备型号：Huawei Mate 30 Pro (LIO-AL00)
 - 设备系统版本：Android 10

**额外有用的信息**
补充额外有用的信息

**Comment by azhon** [comment]
@realskyrin jumpInstallPage(true)已经会自动拉起安装了，你在done的回调里就不需要在拉起安装吧！
不知道是不是你这个引起的

**Comment by realskyrin** [comment]
好的，我把它移掉试试

**Comment by realskyrin** [comment]
移除相关代码后在新版本未出现此类错误，先关掉此 issue

**Comment by realskyrin** [comment]
又出现了 crash
<img width="780" alt="image" src="https://user-images.githubusercontent.com/16552732/165017628-ce4356a4-014f-493c-b5af-bf54226573ba.png">

估计和这里又关系： 
<img width="1238" alt="WeChat08c091bddd6747c90ff69eacda27e0d1" src="https://user-images.githubusercontent.com/16552732/165017869-770157ca-dad9-4fbc-aff1-3eb2723744a7.png">

**Comment by azhon** [comment]
这行代码不至于吧

**Comment by azhon** [comment]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/20559556/167816631-943827c8-1170-4662-9748-b23429aca4b9.png">

<img src="https://user-images.githubusercontent.com/20559556/167816681-a0b44e2f-fdfb-43bc-93d4-dd77ae543049.png"/>

maybe 是这里的问题
