### ISSUE TITLE
DownloadManager空指针

### ISSUE THREAD

**Issue by SoStrongMan** [azhon/AppUpdate#118]
**Bugly自动上报的错误信息：DownloadManager空指针*
该项目已交付使用，目前在Bugly中的数据，总共出现了4次，看手机品牌跟版本号应该是同一个人的手机上报的。

**AppUpdate参数设置**
![image](https://user-images.githubusercontent.com/23330517/167592453-fd98209f-dcbb-418f-9fba-bc1f9d891967.png)

**复现步骤**
都是客户手机自动上报的，本人复现不了。

**错误Logcat日志截图**
![image](https://user-images.githubusercontent.com/23330517/167592639-167f7bd5-ff59-4f82-ae24-333b151f7e1f.png)

**软件版本信息**
 - Android Studio：松鼠、白狐都是这样
 - AppUpdate：4.0.0
 - 设备品牌：HuaWei/EMOTION
 - 设备型号：未知
 - 设备系统版本：Anroid10

**Comment by azhon** [comment]
能复现吗

**Comment by SoStrongMan** [comment]
> 

不能

**Comment by azhon** [comment]
那就是很神奇的问题了

**Comment by azhon** [comment]
[maybe是这个的bug](https://github.com/azhon/AppUpdate/issues/117#issuecomment-1123422178)

**Comment by SoStrongMan** [comment]
> [maybe是这个的bug](https://github.com/azhon/AppUpdate/issues/117#issuecomment-1123422178)

何时能修复呢？我可是对你给予了厚望

**Comment by azhon** [comment]
已经发布了 4.1.0
