### ISSUE TITLE
通知栏提示下载失败

### ISSUE THREAD

**Issue by luyun181** [azhon/AppUpdate#12]
用我们自己的地址下载失败。用您的测试地址就没问题.这个地址应该怎么搞啊？

**Comment by azhon** [comment]
把你的下载地址发给我看下，或者你看下Logcat日志

**Comment by luyun181** [comment]
http://www.ioumxw.com/app/mxw.apk

**Comment by luyun181** [comment]
06-27 17:50:49.077 20654-20654/cn.huanyan.mxwvideo E/DownloadService: 应用的通知栏开关状态：已打开
06-27 17:50:49.216 20654-20774/cn.huanyan.mxwvideo E/DownloadService: error: java.lang.RuntimeException: 获取到的文件大小为0！

**Comment by azhon** [comment]
你看下这篇文章：https://blog.csdn.net/voo00oov/article/details/45821943
你跟你们的后台对一下

**Comment by luyun181** [comment]
这个地址是后台直接返回来的。没有设置head这些。

**Comment by azhon** [comment]
问题已解决 依赖最新版本v1.5.5即可
`
HttpURLConnection设置为gzip方式获取
con.setRequestProperty("Accept-Encoding", "identity");
`
