### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by tx123456** [azhon/AppUpdate#124]
**Bug标题**
Caused by java.lang.NullPointerException

**AppUpdate参数设置**
![image](https://user-images.githubusercontent.com/14331075/177022724-d50af551-4b14-4771-992e-358b52f9f075.png)
![image](https://user-images.githubusercontent.com/14331075/177022733-db9f3d21-b667-4946-b6b3-3bc75aec305a.png)

**复现步骤**
无法复现

**错误Logcat日志截图**
![image](https://user-images.githubusercontent.com/14331075/177022747-c62fcf8a-2aa1-4bb2-87ff-b9fd4c5d49de.png)

**软件版本信息**
 - Android Studio：
 - AppUpdate：4.0.0
 - 设备品牌：
 - 设备型号：
 - 设备系统版本：
 - 
![image](https://user-images.githubusercontent.com/14331075/177022756-0ddb5a36-5981-4b05-9fd3-d736a5b5923f.png)

**额外有用的信息**
补充额外有用的信息

**Comment by azhon** [comment]
已在4.2.0版本优化
