### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by qq987212100** [azhon/AppUpdate#125]
**Bug标题**
downloadmanager会在切到后台下载的时候报内存泄漏，貌似是关闭的时候onDownloadListeners没清空？

**AppUpdate参数设置**
![image](https://user-images.githubusercontent.com/66296430/177071895-f58120d4-2254-4155-9a8e-ce1b148694f8.png)

**复现步骤**
任意位置非强更，点击后台下载即可

**错误Logcat日志截图**
![1656903308264](https://user-images.githubusercontent.com/66296430/177073640-ece3b216-5ba3-45f8-93b5-231103b1bebf.jpg)

**软件版本信息**
 - Android Studio：2021.1.1
 - AppUpdate：4.1.1
 - 设备品牌：
 - 设备型号：
 - 设备系统版本：

**额外有用的信息**
补充额外有用的信息

**Comment by azhon** [comment]
<img width="937" alt="image" src="https://user-images.githubusercontent.com/20559556/177105135-bf86d5b1-29b2-4a36-897f-97a7696cd3ee.png">
不应该啊，加了清理啊

**Comment by qq987212100** [comment]
> <img alt="image" width="937" src="https://user-images.githubusercontent.com/20559556/177105135-bf86d5b1-29b2-4a36-897f-97a7696cd3ee.png">
> 
> 不应该啊，加了清理啊



> <img alt="image" width="937" src="https://user-images.githubusercontent.com/20559556/177105135-bf86d5b1-29b2-4a36-897f-97a7696cd3ee.png">
> 
> 不应该啊，加了清理啊

咱就是说有没有这样一种可能，就是传入的上下文并没有destroy，但是弹窗本身销毁了，导致本来应该clear的观察者list并没有clear，
![1B1C882F](https://user-images.githubusercontent.com/66296430/177108135-b1d16bd2-fb92-4f3d-b82f-6e296380ecfc.gif)

**Comment by azhon** [comment]
来进个qq群828385813，改好了来测试下看行不行
