### ISSUE TITLE
可否允许在没有设置VersionCode的情况下也显示界面？

### ISSUE THREAD

**Issue by zhbzhbzhbz** [azhon/AppUpdate#126]
如题，因为很希望用内置的对话框，但是我们的更新服务又不会返回给客户端新的VersionCode（因为他们为了多客户端统一，只会使用一个VersionName）。
刚刚试了下：为了强制触发对话框，apkVersionCode就只能设置为Integer.MAX_VALUE

**Comment by azhon** [comment]
那你可以这么设置，然后在外面判断是否需要进行更新，或者你把对话框代码拷出来自己些对话框
