### ISSUE TITLE
[建议] apkSize参数改为long，或末尾不附加"M"

### ISSUE THREAD

**Issue by zhbzhbzhbz** [azhon/AppUpdate#127]
由于一般更新接口返回的fileSize是long，而Android自带的"bytes转MB"的API: `android.text.format.Formatter.formatShortFileSize(@Nullable Context context, long sizeBytes) `返回的格式是类似 `30MB` 这种；
但是当前apkSize函数接收的参数预设了是数字，会跟"M"拼接，这样会导致用起来比较麻烦，如果传入上面的系统API的结果，对话框上显示的字符串就会是`30MBM`；而且如果apk很小（<0.9MB），上述API返回的单位就会是KB
所以建议把apkSize参数改为long，或末尾不再附加"M"

刚刚打赏了~ 感谢作者

**Comment by azhon** [comment]
好的 下个版本我把"M"去了。目前你可以在对应的string.xml文件中取相同名字进行覆盖
`<string name="dialog_new_size"></string>`

**Comment by azhon** [comment]
使用4.2.1版本即可了
