### ISSUE TITLE
你的demo有点问题

### ISSUE THREAD

**Issue by tvvbbb** [azhon/AppUpdate#13]
在我的机器上，你的demo如果先点击了使用版本内置的对话框更新，再点击另外两个按钮，就会出现出现版本库内置的对话框，这个非常的古怪

**Comment by azhon** [comment]
应该是DownloadManager 对象是同一个导致的，没有组做处理。这个问题不影响实际使用

**Comment by tvvbbb** [comment]
影响到了demo的表现，希望修正，而且好像没有提供默认的下载进度条，还有自动安装的功能

**Comment by azhon** [comment]
好的。进度条和自动安装都有的

**Comment by tvvbbb** [comment]
不是通知栏的进度条，在demo也是自己写的progressbar

**Comment by tvvbbb** [comment]
好的
