### ISSUE TITLE
弹窗背景

### ISSUE THREAD

**Issue by fuys123** [azhon/AppUpdate#131]
**Bug标题**
清楚简明的描述你遇到的问题

**AppUpdate参数设置**
截图`DownloadManager`配置

**复现步骤**

**错误Logcat日志截图**  
![IMG_20220906_165022](https://user-images.githubusercontent.com/16770953/188591641-7041c0f0-228a-487a-9ef2-b9950d790330.jpg)

日志截图

**软件版本信息**
 - Android Studio：
 - AppUpdate：
 - 设备品牌：mi
 - 设备型号： 
 - 设备系统版本：

**额外有用的信息**
补充额外有用的信息

**Comment by azhon** [comment]
背景是黑的？

**Comment by fuys123** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by fuys123** [comment]
> 背景是黑的？

嗯测试发现的，最新版的4.2.2

**Comment by azhon** [comment]
小米啥型号的？其它设备会吗？或者你加下群细说下：828385813

**Comment by fuys123** [comment]
> 小米啥型号的？其它设备会吗？或者你加下群细说下：828385813

mi8与mi11pro都一样的情况，目前没拿其他手机测。

**Comment by azhon** [comment]
我这使用Mi 10 Android 11没有问题，你可以看下能不能抓取到对应的错误日志

**Comment by fuys123** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
