### ISSUE TITLE
优化：DownloadManager Builder 构造依赖Activity问题

### ISSUE THREAD

**Issue by designerMichael** [azhon/AppUpdate#132]
可否改成依赖Context?

**Comment by azhon** [comment]
<img width="554" alt="image" src="https://user-images.githubusercontent.com/20559556/189788141-d078eec9-fd00-47a6-970e-7d14e736a7d7.png">
不能，为了解决宿主Activity关闭导致的内存泄漏问题需要Activity Class的类名
