### ISSUE TITLE
BUG 下载出现异常时，下载对话框无法关闭

### ISSUE THREAD

**Issue by akingyin1987** [azhon/AppUpdate#135]
download error: java.net.ProtocolException: unexpected end of stream
出现异常后就卡在那了，无法退出，OnDownloadListenerAdapter 这个监听没有处理异常

**Comment by akingyin1987** [comment]
你这个通知栏应该没有做适配吧，我android 13 的模拟 器不会显示

**Comment by azhon** [comment]
对话框无法关闭 你是强制更新吧？

你可以看下app是否打开了通知开关

**Comment by akingyin1987** [comment]
是强制更新，但这种网络异常或下载失败时也得处理下，要不就卡在那退不了

**Comment by azhon** [comment]
嗯，后面我看一下

**Comment by azhon** [comment]
[已在4.2.4版本修复](https://github.com/azhon/AppUpdate/commit/8f5515a075939840c8ccd7064e6b460f118744b2)
