### ISSUE TITLE
升级到最新AS插件版本后，依赖4.2.3版本编译通不过

### ISSUE THREAD

**Issue by SoStrongMan** [azhon/AppUpdate#136]
**Bug标题**
Android Studio升级到海豚版本，插件升级到了7.3.0版本，Gradle版本是7.4，依赖最新的4.2.3版本，编译通不过，报“java.lang.RuntimeException: Using multiple versions of the Android Gradle plugin(7.1.2, 7.3.0) in the same build is not allowed”

**复现步骤**
按照Bug标题内容集成，百分百复现

**错误Logcat日志截图**
![image](https://user-images.githubusercontent.com/23330517/192188501-b06a94dd-e76f-42a5-ba14-17861b903235.png)

**软件版本信息**
 - Android Studio：Android Studio Dolphin | 2021.3.1
 - AppUpdate：io.github.azhon:appupdate:4.2.3

**额外有用的信息**
就算是把AS插件版本、Gradle版本降级到之前没出问题的版本号，只要升级到4.2.3版本，还是报同样的问题。

**Comment by azhon** [comment]
把插件版本降到7.1.2即可
<img width="640" alt="image" src="https://user-images.githubusercontent.com/20559556/192214223-1e629385-27d6-4a94-b008-8be8ca8b893e.png">

**Comment by azhon** [comment]
待研究研究🧐

**Comment by SoStrongMan** [comment]
> 待研究研究🧐

加油，看好你！修复这个问题，我觉得至关重要！！！

**Comment by luyun181** [comment]
++1

**Comment by azhon** [comment]
[已在4.2.4版本修复](https://github.com/azhon/AppUpdate/commit/f74c95df75391d4eefd8c22546e4d93ff5bdd055)
