### ISSUE TITLE
是否考虑一下支持低版本的kotlin引用

### ISSUE THREAD

**Issue by JoinLi** [azhon/AppUpdate#138]
/Users/.gradle/caches/transforms-2/files-2.1/16e098705f00c7a68512c8317510ec71/jetified-kotlin-stdlib-common-1.7.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.4.0.

**Comment by azhon** [comment]
不考虑，肯定是用新版本。

**Comment by ff-frida** [comment]
> /Users/.gradle/caches/transforms-2/files-2.1/16e098705f00c7a68512c8317510ec71/jetified-kotlin-stdlib-common-1.7.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.4.0.

我也遇到这个了，就不打算用这个库了
