### ISSUE TITLE
BUG：引用之后无法找到问题

### ISSUE THREAD

**Issue by AndroidBody** [azhon/AppUpdate#139]
**Bug标题**
清楚简明的描述你遇到的问题

**AppUpdate参数设置**
截图`DownloadManager`配置

**复现步骤**

**错误Logcat日志截图**
日志截图

**软件版本信息**
 - Android Studio：
 - AppUpdate：
 - 设备品牌：
 - 设备型号：
 - 设备系统版本：

**额外有用的信息**
补充额外有用的信息

**Comment by zhangsan2016** [comment]
可以把你的  Min Dart SDK 版本再调低一点吗？

**Comment by azhon** [comment]
> 可以把你的 Min Dart SDK 版本再调低一点吗？

16已经很低了
