### ISSUE TITLE
为什么http 下载连接不行

### ISSUE THREAD

**Issue by Andjdd** [azhon/AppUpdate#140]
为什么http 下载连接不行  点击下载没用反应

  manager.setApkName("text.apk")
                .setApkUrl(url)
                .setSmallIcon(R.mipmap.ic_launcher)
                .setShowNewerToast(true)
                .setConfiguration(configuration)
//                .setDownloadPath(Environment.getExternalStorageDirectory() + "/AppUpdate")
                .setApkVersionCode(Integer.parseInt(versioncode))
                .setApkVersionName(apkVersionName)
                .setApkSize(apkSize)
                .setAuthorities(getPackageName())
                .setApkDescription(descriptionReplace)
                .download();

**Comment by azhon** [comment]
一看用的就是旧版本，用新版本
