### ISSUE TITLE
在某些设备会提示 Permission deied

### ISSUE THREAD

**Issue by log2c** [azhon/AppUpdate#142]
在某些设备会提示 Permission deied，也有可能是小米魔改导致

**Log or something else**
```
download error: java.io.FileNotFoundException: /storage/emulated/0/Android/data/{package_name}/cache/v10002_1.0.2.apk: open failed: EACCES (Permission denied)
```
**Software version**
 - Android Studio：
 - AppUpdate Version：4.2.5
 - Device Brand：小米电视
 - Device Model：
 - Android Version：6.0.1

**Comment by azhon** [comment]
看起是路径没有生成对`/storage/emulated/0/Android/data/{package_name}/cache/`，`{package_name}`没有被替换到，
你可以跑下Demo看看这行代码[DownloadManager](https://github.com/azhon/AppUpdate/blob/main/appupdate/src/main/java/com/azhon/appupdate/manager/DownloadManager.kt#L81)执行结果

**Comment by log2c** [comment]
> 

不是，{package_name}只是我app的名称，已经正确生成了地址。

搜了下，发现一个其它项目 类似的issues https://github.com/TeamAmaze/AmazeFileManager/issues/2015
但是我这是 6.0.1，很灵异

我再尝试解决下

**Comment by azhon** [comment]
噢噢，那你尝试看下要怎么处理

**Comment by log2c** [comment]
需要
```
MANAGE_EXTERNAL_STORAGE
```
权限

**Comment by wangzhi17** [comment]
能否自定义下载路径，某些设备没有申请存储权限，会安装失败

**Comment by azhon** [comment]
这个缓存路径都不需要权限的呀😰
