### ISSUE TITLE
狗就是狗，无需多说，垃圾人造垃圾轮子！！！

### ISSUE THREAD

**Issue by q88qaz** [azhon/AppUpdate#143]
自己没本事还不让说？
垃圾就算了，还做这么一堆垃圾轮子浪费别人的时间
就这种破轮子，谁用谁倒霉！！！
没本事就玩权限是吧
预祝你妈早日爆炸！
预祝你爸做鸭起早贪黑！！！！
凸( •̀ 3 •́ )凸

**Comment by azhon** [comment]
肏你妈，你个垃圾社会败类

**Comment by Amyitis** [comment]
开源免费的库~爱用用~不爱用就滚，一分钱没收你的~你还来这么秀人品的下限！

**Comment by why168** [comment]
别骂人！和气生财！好好做开源事业

**Comment by thebestRaven** [comment]
沙雕，也不想想你是怎么进群的？不是为了用这个库？不懂得感激？真是放下饭碗就骂娘？ 垃圾库？ 垃圾你就说说垃圾的地方，让作者修改，还是说不出来？单纯为了骂？？真是沙雕

**Comment by lodgkk** [comment]
我第一次看到用了免费的开源库,还骂人家的,你心眼小得,懂得感恩,懂得做人,不懂就从新从学做人开始,别丢人现眼

**Comment by moshangpiaoxue** [comment]
都白嫖了，还嫌弃人活不好？

**Comment by moshangpiaoxue** [comment]
都白嫖了，还嫌弃人活不好？

**Comment by himym1** [comment]
太贱了吧。。还跑这里来骂

**Comment by MarkRaoAndroid** [comment]
在网上各种喷，这么低素质的程序员，一看就是菜鸡

**Comment by azhon** [comment]
[原来这SB在这就开始骂了呀，难怪啊](https://github.com/gzu-liyujiang/AndroidPicker/issues/291)

**Comment by wszpwsren** [comment]
资瓷裱起来

**Comment by OrangeBoys** [comment]
别在网络喷,有本事线下来.

**Comment by AndroidBreathing** [comment]
自己有能力写一个轮子 不就送你一张飞机票吗 至于吗 心理变态啊

**Comment by yhf1414104530** [comment]
> 
白嫖🐶还振振有词，脸皮不是一般的厚

**Comment by JasonYinH** [comment]
这是哪个公司的程序员，先做人好吧，支持开源作者

**Comment by lifuyuan123** [comment]
我是大自然的搬运工
[图1](https://github.com/ListerChen/RecyclerViewDemo/issues/1) [图2](https://github.com/yhaolpz/FloatWindow/issues/128)
![image](https://user-images.githubusercontent.com/22439151/208803535-81474e96-5c61-4421-a8e0-bc82afd794e3.png)
![image](https://user-images.githubusercontent.com/22439151/208803624-be46fd07-d5b8-4b68-9faf-7e6fea7c1b51.png)

**Comment by AndroidHensen** [comment]
@q88qaz 出来回一下我

**Comment by pengbig** [comment]
吃完饭砸锅的傻逼？

**Comment by liyujiang-gzu** [comment]
> [原来这SB在这就开始骂了呀，难怪啊](https://github.com/gzu-liyujiang/AndroidPicker/issues/291) ![image](https://user-images.githubusercontent.com/20559556/208621245-0c9e6b6b-8901-4514-8441-74baf97b8368.png)

好心开源出来给别人用，不帮忙改进也就算了，还搞负能量影响心情，那时候我心都凉了，心灰意冷。

**Comment by azhon** [comment]
哎呦 你这个傻b 还来改标题了啊 新的一年祝你越来越傻b，祝你妈了个逼的 @q88qaz
