### ISSUE TITLE
你好，请问能否支持弹窗是Dialog方式

### ISSUE THREAD

**Issue by zhanghuibiao** [azhon/AppUpdate#145]
现在有一种情形是在onResume中调用检测更新，等更新完成点击稍后安装，还会触发onResume，此时又会检测更新

**Comment by azhon** [comment]
不能，这个你直接在onResume中判断`DownloadManager`是否创建过就可以规避

**Comment by zhanghuibiao** [comment]
> 不能，这个你直接在onResume中判断`DownloadManager`是否创建过就可以规避

<img width="407" alt="image" src="https://user-images.githubusercontent.com/19171770/219264610-5be0ded3-586a-4965-a72a-e91e09f4e9d8.png">
这里每次走build的时候会先release, DownloadManager会重新创建

**Comment by azhon** [comment]
那你可以自己加个变量来控制
