### ISSUE TITLE
Change Language to Spanish

### ISSUE THREAD

**Issue by jfrangonzalez94** [azhon/AppUpdate#147]
**AppUpdate parameter**
Screenshot `DownloadManager` configuration

**Change Language to Spanish**
Hello how are you, how can I customize the language, I want to change it to Spanish but it won't let me, I would really appreciate it.

**Software version**
 - Android Studio： 2022.1.1
 - AppUpdate Version：4.2.8
 - Device Model：Samsung A32
 - Android Version：12

**Comment by jfrangonzalez94** [comment]
Off topic friend, is this progress bar not enabled?

![image](https://user-images.githubusercontent.com/25354001/226675872-90f96010-ad06-4941-b074-1d1f0a8ec99a.png)

**Comment by azhon** [comment]
Need to set `DownloadManager.forcedUpgrade = true`

**Comment by jfrangonzalez94** [comment]
Thank you very much friend, I was able to solve the 2 doubts, I appreciate it.
