### ISSUE TITLE
现在最新版本的下载没有弹窗吗  直接后台下载？

### ISSUE THREAD

**Issue by gitboylovegirl** [azhon/AppUpdate#153]
**AppUpdate parameter**
Screenshot `DownloadManager` configuration

**Steps to reproduce**

**Log or something else**

**Software version**
 - Android Studio：
 - AppUpdate Version：
 - Device Brand：
 - Device Model：
 - Android Version：

**Comment by azhon** [comment]
<img width="838" alt="image" src="https://github.com/azhon/AppUpdate/assets/20559556/d658bb97-7193-44d9-8738-7f49507af80b">
