### ISSUE TITLE
'void com.azhon.appupdate.listener.OnDownloadListener.start()' on a null object reference  com.azhon.appupdate.manager.HttpDownloadManager.fullDownload(HttpDownloadManager.java:86)

### ISSUE THREAD

**Issue by xushufeng** [azhon/AppUpdate#155]
**AppUpdate parameter**
Screenshot `DownloadManager` configuration

**Steps to reproduce**

**Log or something else**

**Software version**
 - Android Studio：
 - AppUpdate Version：
 - Device Brand：
 - Device Model：
 - Android Version：

**Comment by azhon** [comment]
建议使用最新版本
