### ISSUE TITLE
Googleplay版本具体是要去除哪些功能才可以上架？

### ISSUE THREAD

**Issue by gnmmdk** [azhon/AppUpdate#158]
如题，我是使用自己的更新功能，但是被google拒绝了。目前我们app的逻辑是：通过自己的接口判断是否有新版本需要升级，有的话跳转到Googleplay进行升级。

**Comment by azhon** [comment]
看Readme说明，使用步骤，第一步

**Comment by gnmmdk** [comment]
我有看到哦，我是想咨询下：如果我们app仅仅是跳转到Googleplay进行升级，而没有下载apk的动作，是否可以审核通过？

**Comment by gnmmdk** [comment]
我有看到no-op的代码，基本上是没有功能了。

**Comment by azhon** [comment]
> 我有看到no-op的代码，基本上是没有功能了。
> 
> 

是的

**Comment by azhon** [comment]
> 我有看到哦，我是想咨询下：如果我们app仅仅是跳转到Googleplay进行升级，而没有下载apk的动作，是否可以审核通过？

可以的，不要有安装apk权限，不要有安装apk代码

**Comment by gnmmdk** [comment]
主要是安装代码我也去掉了，例如这个方法：
 @JvmStatic
    fun installApk(context:Context,apkPath: String?) {

        if (apkPath.isNullOrEmpty()) return

        val intent = Intent(Intent.ACTION_VIEW)
        val apkFile = File(apkPath)

        // android 7.0 fileprovider 适配
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            val contentUri =
                FileProvider.getUriForFile(context, context.packageName + ".update.fileprovider", apkFile)
            intent.setDataAndType(contentUri, "application/vnd.android.package-archive")
        } else {
            intent.setDataAndType(Uri.fromFile(apkFile), "application/vnd.android.package-archive")
        }

        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        context.startActivity(intent)
    }
不过我只去除上方的安装代码以及安装的权限。
下载功能和md5校验以及大部分其他功能，我并没有去除，但是还是被googleplay审核打回了。

**Comment by azhon** [comment]
那就不太清楚了，可以按下谷歌的审核是怎么检测这一块的
