### ISSUE TITLE
现在安装apk还需要判断版本去设置里打开安装未知来源应用权限吗？

### ISSUE THREAD

**Issue by HycHcl** [azhon/AppUpdate#164]
Uri packageURI = Uri.parse("package:" + context.getPackageName());
Intent intent = new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES, packageURI);
这个跳转设置打开安装未知来源应用权限的逻辑还需要吗？求问， 还是说直接调用安装的方法就可以，不太清楚

**Comment by azhon** [comment]
下载完成的时候，默认会自动跳到App设置`允许未知来源`页面。
当然你也可以在下载之前判断权限 对用户进行引导

**Comment by wzgl5533** [comment]
但我发现 我的APP没有授权未知安装，也能直接安装
