### ISSUE TITLE
有兼容Androd14吗

### ISSUE THREAD

**Issue by 530l** [azhon/AppUpdate#167]
**AppUpdate parameter**
Screenshot `DownloadManager` configuration

**Steps to reproduce**

**Log or something else**

**Software version**
 - Android Studio：
 - AppUpdate Version：
 - Device Brand：
 - Device Model：
 - Android Version：

**Comment by azhon** [comment]
Android 14这一块应该没有改动，你可以测试一下，没有问题就是兼容的
