### ISSUE TITLE
appupdate-no-op中的ApkUtil类中没暴露installApk接口。

### ISSUE THREAD

**Issue by RunliSong** [azhon/AppUpdate#168]
**具体现象**
同时引入appupdate和appupdate-no-op之后，在代码中调用ApkUtil.Companion.installApk()接口，google渠道编译报错，未找到符号。
之后看到是因为appupdate-no-op的ApkUtil类中未实现installApk方法，不知是什么原因？

**Steps to reproduce**

**Log or something else**

**Software version**
 - Android Studio：
 - AppUpdate Version：
 - Device Brand：
 - Device Model：
 - Android Version：

**Comment by azhon** [comment]
你是自己调用了这个installApk方法吗？

**Comment by RunliSong** [comment]
是的，只使用了下载功能，下载完成后，手动调用的安装功能

**Comment by azhon** [comment]
那你先自己判断一下渠道在调用installApk方法，后面我把这个加上去

**Comment by RunliSong** [comment]
ok

**Comment by azhon** [comment]
使用最新的4.3.4版本即可
