### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by FrankLove** [azhon/AppUpdate#169]
大佬，我用的as 2023.1.1版本，引用你这个库后编译报错，这是什么原因
 A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\zheng\.gradle\caches\transforms-2\files-2.1\6a7713d8e65b6c716a9f3848f4c2a959\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

我的插件版本是
classpath 'com.android.tools.build:gradle:3.5.2'
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip

**Comment by azhon** [comment]
估计你得升升版本吧，这都是多少年前的版本了🫠

**Comment by FrankLove** [comment]
好的，确实很老了

**Comment by superoidlau** [comment]
升到哪个版本了？
