### ISSUE TITLE
切换窗口模式会导致Update Dialog Activity不显示

### ISSUE THREAD

**Issue by NasdaqGodzilla** [azhon/AppUpdate#170]
**AppUpdate parameter**
不好意思，无法提供。因为我是Android系统层，发现某App使用贵SDK后出现的问题。贵SDK接受的参数情况，遗憾无法提供

**Steps to reproduce**
1. 触发App的Update流程
2. 等待弹出升级信息Dialog Activity
3. 切换App的显示模式（Windowing Mode, e.g. 在Fullscreen和freeform之间切换）

**Log or something else**
There are no any logs.

**Software version**
 - Android Studio：/
 - AppUpdate Version：/
 - Device Brand：AOSP
 - Device Model：/
 - Android Version：Android 10/11/14均复现

期待您的回复

**Comment by azhon** [comment]
这个估计是Activity被销毁了，需要重新再次创建吧？

**Comment by wsdydeni** [comment]
> 这个估计是Activity被销毁了，需要重新再次创建吧？

进来就看到新鲜的Bug 哈哈

**Comment by NasdaqGodzilla** [comment]
> 这个估计是Activity被销毁了，需要重新再次创建吧？

但是背景的变暗效果是在的，而且Activity也在，没有销毁的。
是有其他原因导致没有弹窗吗？或者弹窗的大小、位置有点异常

**Comment by azhon** [comment]
就是Activity的window大小变化了，会影响。
有出问题的录屏吗，看看

**Comment by NasdaqGodzilla** [comment]
> 就是Activity的window大小变化了，会影响。 有出问题的录屏吗，看看

我使用SDK里面的Demo App是正常的。这看起来是应用方自己修改出来的问题。issue先关闭了，感谢您的支持。
