### ISSUE TITLE
增加下载成功后退出重新进来不用再次下载的功能

### ISSUE THREAD

**Issue by wsdydeni** [azhon/AppUpdate#171]
**AppUpdate parameter**
Screenshot `DownloadManager` configuration

**Steps to reproduce**

**Log or something else**

**Software version**
 - Android Studio：
 - AppUpdate Version：
 - Device Brand：
 - Device Model：
 - Android Version：

**Comment by wsdydeni** [comment]
@azhon

**Comment by azhon** [comment]
参数设置一下apk的md5值即可，就不会重复下载
