### ISSUE TITLE
增加打开应用商店更新的按钮

### ISSUE THREAD

**Issue by wsdydeni** [azhon/AppUpdate#172]
**AppUpdate parameter**
Screenshot `DownloadManager` configuration

**Steps to reproduce**

**Log or something else**

**Software version**
 - Android Studio：
 - AppUpdate Version：
 - Device Brand：
 - Device Model：
 - Android Version：

**Comment by wsdydeni** [comment]
@azhon

**Comment by azhon** [comment]
这个不具有固定性、普遍性。
建议参照Demo中`使用自己的对话框更新`案例，自己写个对话框，想跳哪就跳哪。
