### ISSUE TITLE
刚打开能够默认不显示更新的进度条吗

### ISSUE THREAD

**Issue by wsdydeni** [azhon/AppUpdate#173]
**AppUpdate parameter**
Screenshot `DownloadManager` configuration

**Steps to reproduce**

**Log or something else**

**Software version**
 - Android Studio：
 - AppUpdate Version：
 - Device Brand：
 - Device Model：
 - Android Version：

**Comment by wsdydeni** [comment]
@azhon

**Comment by azhon** [comment]
哪个地方的进度条？

**Comment by wsdydeni** [comment]
> 哪个地方的进度条？

下载进度条，刚弹出没有开始下载就会显示。

**Comment by azhon** [comment]
可以考虑自己实现个对话框
