### ISSUE TITLE
是否支持完全自定义样式的对话弹出框样式

### ISSUE THREAD

**Issue by SoStrongMan** [azhon/AppUpdate#175]
【描述】
从4.3.1版本开始，适配了pad端对话框，这时候去重写xml样式，在pad中会导致显示不全。
【问】
是否支持完全自定义样式xml？
【需求说明】
实际项目中，框架定义的样式结构大概率无法满足设计需求，因此需要重新绘制布局。

**Comment by azhon** [comment]
参考 使用自己的对话框 示例

**Comment by SoStrongMan** [comment]
看了源码，UpdateDialogActivity中setWindowSize方法，写死了window的宽度。是否可以设置一个自定义弹窗宽度的参数，如果传入就用这个值，没有就用默认的。因为很多时候，可能只是单纯的替换一些控件或者加一些控件，写死的宽度就会导致显示异常。

**Comment by azhon** [comment]
所以很难适配所有的人 所有的需求，建议自己自定义，实在不行 源代码依赖使用

**Comment by bigmoon929** [comment]
> 参考 使用自己的对话框 示例

您好，示例在哪里呢？

**Comment by azhon** [comment]
这个仓库代码看不到吗？
