### ISSUE TITLE
小米8  一直下载完成之后一直提示下载出错是什么情况大佬

### ISSUE THREAD

**Issue by xiaojianren1993** [azhon/AppUpdate#19]

**Comment by azhon** [comment]
查下log，应该是安装出错了，你是不是少配置了什么

**Comment by xiaojianren1993** [comment]
都按着你说的配置了 用的你的默认的AppUpdate路径配置的。 也是调用的简单的那个下载  方便留一下联系方式么大佬

**Comment by azhon** [comment]
你看下Logcat的日志

**Comment by xiaojianren1993** [comment]
解决了，谢谢大佬的库 是我自己的问题  AndroidMainifest 里的authorities的值没有设置对。
