### ISSUE TITLE
如何判断版本

### ISSUE THREAD

**Issue by beginWith** [azhon/AppUpdate#2]
请问一下 你是如何判断系统版本的?code?还是name? 我试过把你的代码code和name改为100 但是还是进行了下载,,,,

**Comment by azhon** [comment]
判断的是VersionCode

**Comment by azhon** [comment]
[仔细看下文档](https://github.com/azhon/AppUpdate#downloadmanager%E9%85%8D%E7%BD%AE%E6%96%87%E6%A1%A3)

**Comment by beginWith** [comment]
是的 我也看到了 但是如同我所说的 我已经改为100了 还是可以下载, 难道你挂着的apk code的设置大过了100?

**Comment by azhon** [comment]
` DownloadManager manager = DownloadManager.getInstance(this);
        manager.setApkName("appupdate.apk")
                .setApkUrl("https://raw.githubusercontent.com/azhon/AppUpdate/master/apk/appupdate.apk")
                .setSmallIcon(R.mipmap.ic_launcher)
                .setShowNewerToast(true)
                .setConfiguration(configuration)
                .setDownloadPath(Environment.getExternalStorageDirectory() + "/AppUpdate")
                .setApkVersionCode(2)
                .setApkVersionName("2.1.8")
                .setApkSize("20.4")
                .setApkDescription("1.支持断点下载\n2.支持Android N\n3.支持Android O\n4.支持自定义下载过程\n5.支持 设备>=Android M 动态权限的申请\n6.支持通知栏进度条展示(或者自定义显示进度)")
                .download();
`
setApkVersionCode 这个就是你从服务器获取的最新版本号，如果大于了本地安装好的apk versionCode 就会提示更新.....

**Comment by beginWith** [comment]
我知道了 谢谢 没有考虑周全
