### ISSUE TITLE
小米手机经常 解析软件包时出现问题

### ISSUE THREAD

**Issue by HuRuWo** [azhon/AppUpdate#22]
请问如何解决

**Comment by azhon** [comment]
查看下Logcat的日志

**Comment by HuRuWo** [comment]
这个是系统弹出的提示 没有看到日志
个人认为是点击下载文件过快导致的 可能文件还没完全下载完 
如果随后在通知栏点击文件安装是没有问题的

**Comment by azhon** [comment]
如果没有下载完成，通知栏点击是没有设置intent的

**Comment by HuRuWo** [comment]
请问如果设置不自动弹出安装界面 我想等10秒再去点击文件安装 如何操作

**Comment by azhon** [comment]
设置下载完成监听 然后写个计时器
