### ISSUE TITLE
为啥每到进度条完成成时就出错

### ISSUE THREAD

**Issue by hellowolrds** [azhon/AppUpdate#23]
试了N次，每次都是进度条完成之后通知栏就显示下载失败，模拟器上可以，真机不行，我的是小米手机

**Comment by hellowolrds** [comment]
E/AppUpdate.DownloadService: error: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
W/System.err:     at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:604)

**Comment by hellowolrds** [comment]
空指针

**Comment by azhon** [comment]
![f25f1a37-d11d-4733-8a00-748577b82b1f](https://user-images.githubusercontent.com/20559556/47960053-9c49cd80-e02e-11e8-9a11-62f9a5f5bf53.png)
配置下uri撒......

**Comment by hellowolrds** [comment]
我已经改好了，刚刚百度搜了一下，谢谢啊兄弟
