### ISSUE TITLE
功能 || 需求征集贴

### ISSUE THREAD

**Issue by azhon** [azhon/AppUpdate#25]
大家对于这个库有什么想法 || 需要什么功能 || 需要改进什么，欢迎来这里留言!!!😇

**Comment by yk963307153** [comment]
我有个小建议，就是app更新下载完没有安装，退出去app之后再次进来，升级不是直接去安装，而是又去重新下载了

**Comment by azhon** [comment]
判断文件存在 && 校验md5看文件是否完全下载完成 && 获取apk文件的versionCode 与你要下载的是否一致

**Comment by yk963307153** [comment]
我刚开始只是想到了判断文件存在，没想到校验md5这些，还挺麻烦

**Comment by AnJeremy** [comment]
下载失败后，是否有重试的下载次数

**Comment by azhon** [comment]
没有，下载失败会在通知栏发送一个失败通知，点击可以继续下载

**Comment by AnJeremy** [comment]
但是我们要求不能显示通知栏的呀

**Comment by azhon** [comment]
那你可以监听下载过程，然后失败再次启动下载

**Comment by AnJeremy** [comment]
好的 ，我还想说一句就是下载速度确实有点慢

**Comment by AnJeremy** [comment]
如何下载取消？

**Comment by azhon** [comment]
还不支持，为什么有这个需求？

**Comment by AnJeremy** [comment]
应用退出取消下载，要不然应用退出了，下载完成后自动安装会出问题的

**Comment by azhon** [comment]
下载是后天服务下载，你现在是出什么问题了？

**Comment by AnJeremy** [comment]
activity都被销毁 在安装就直接报空呀

**Comment by azhon** [comment]
我这测试了不会，你是做了什么？

**Comment by AnJeremy** [comment]
在下载完成后弹出更新按钮

**Comment by azhon** [comment]
很优秀

**Comment by azhon** [comment]
> 如何下载取消？
现在v2.0.0版本支持取消下载了

**Comment by azhon** [comment]
现在v2.0.0版本支持取消下载了
