### ISSUE TITLE
安卓8.0，import android.support.v7.app.AlertDialog; 引入这个包，会报

### ISSUE THREAD

**Issue by azhon** [azhon/AppUpdate#26]
![image](https://user-images.githubusercontent.com/29586966/48383427-aa7ba600-e720-11e8-9f10-24f782cc9efd.png)
![image](https://user-images.githubusercontent.com/29586966/48383451-bd8e7600-e720-11e8-9247-57b76c9c42af.png)

_Originally posted by @wubodanran in https://github.com/azhon/AppUpdate/issues/25#issuecomment-438085728_

能否根据apkVersionName判断，是否最新版，或者能直接下载，不需要判断

**Comment by wubodanran** [comment]
那能不能设置不判断apkVersionCode,直接就下载

**Comment by azhon** [comment]
可以啊大哥，看文档 看demo啊....

**Comment by azhon** [comment]
你把地址发给我看下....

**Comment by wubodanran** [comment]
https://www.wubo777.top/api/imm-api/upload/imm-1.0.5.apk

**Comment by azhon** [comment]
使用最新的v1.7.3版本可以了

**Comment by wubodanran** [comment]
好的，可以了
