### ISSUE TITLE
功能 || 需求征集贴

### ISSUE THREAD

**Issue by azhon** [azhon/AppUpdate#28]
大家有什么好的建议或需求欢迎提出！

**Comment by byc4426** [comment]
支持强制更新吗

**Comment by wubodanran** [comment]
下载链接超时，是否可以增加一个重试.

**Comment by NerdAnonymous** [comment]
静默下载来一发

**Comment by NerdAnonymous** [comment]
还有版本忽略

**Comment by azhon** [comment]
> 静默下载来一发

静默下载是支持的，不显示通知，直接调用下载即可

**Comment by NerdAnonymous** [comment]
还有个小问题，强制下载，下载完成后如果用户取消安装，弹窗一直显示的是正在后台下载新版本，这时候最好变成安装应用，然后点击直接安装应用

**Comment by protectedMan** [comment]
同此需求

**Comment by protectedMan** [comment]
> 还有个小问题，强制下载，下载完成后如果用户取消安装，弹窗一直显示的是正在后台下载新版本，这时候最好变成安装应用，然后点击直接安装应用

同此需求
