### ISSUE TITLE
问题 || Bug反馈贴

### ISSUE THREAD

**Issue by azhon** [azhon/AppUpdate#29]
大家在使用中遇到了什么问题欢迎留言

**Comment by Cool-Yang** [comment]
强制更新

**Comment by azhon** [comment]
这个功能，已经有了

**Comment by ichapter** [comment]
您好，感谢你开发的更新库，有这样一个建议：
App下载完，进入到安装页面，在安装页面点击取消按钮再次返回到App内时，这时再次点击弹窗的更新按钮，点击没效果，是否可以点击的时候直接进入到安装页面呢，辛苦啦

**Comment by azhon** [comment]
你是设置了强制更新吗！，如果是的话，这种情况直接退出应用，在进入就可以了；
如果你必须要实现的话，那就自己定义那个对话框（可以把源码的对话框拷贝出来改改）

**Comment by ichapter** [comment]
@azhon 好，感谢开源，头像好萌啊

**Comment by xushengjiang0** [comment]
我用最简单的模式，我(测试人员)想取消底部那个Toast(正在后台更新..)，我没找到设置方法。请问可以取消吗。

**Comment by azhon** [comment]
这个提示如果设置了显示通知了进度就会显示这个Toast，不显示通知就不会。
看来这里得再加个Boolean值了

**Comment by xushengjiang0** [comment]
> 这个提示如果设置了显示通知了进度就会显示这个Toast，不显示通知就不会。
> 看来这里得再加个Boolean值了

这个库很好用，我是用RN写东西，界面都由RN来写，Android就会集成。

**Comment by Iridescentangle** [comment]
问一下噢，该应用本身有请求读写外置存储的权限，这个库里是集成了的
为了测试，我在启动应用时候拒绝了读写外置存储的权限，为啥更新还能正常下载呢...好神奇啊，怎么做到的

**Comment by azhon** [comment]
> 问一下噢，该应用本身有请求读写外置存储的权限，这个库里是集成了的
> 为了测试，我在启动应用时候拒绝了读写外置存储的权限，为啥更新还能正常下载呢...好神奇啊，怎么做到的

那你是否设置了文件下载保存目录，如果没有的话默认使用`getExternalCacheDir()`这个目录是不需要权限的

**Comment by azhon** [comment]
> 您好，我是个新手，引用了您MainActivity里的update3()，可是dialog没显示出来，能请您帮下忙吗？

设置个VersionCode > 1 的值就可以了

**Comment by hanouba** [comment]
清单文件中FileProvider 能将 android:authorities="${applicationId}" 修改为 android:authorities="${applicationId}.provider" 吗 或者自定义吗

**Comment by azhon** [comment]
> 清单文件中FileProvider 能将 android:authorities="${applicationId}" 修改为 android:authorities="${applicationId}.provider" 吗 或者自定义吗

使用最新版本 是可以的

**Comment by supersugar** [comment]
bugly上收到一个bug:
```
java.lang.RuntimeException:Unable to start service com.azhon.appupdate.service.DownloadService@3c59eb0 with Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.yutong.xny/com.azhon.appupdate.service.DownloadService }: java.lang.RuntimeException: 请先调用 getInstance(Context context) !
```
版本是1.7.3,不知道最新版的有没有解决,望回复~谢谢~

**Comment by azhon** [comment]
这个就有可能是 `DownloadManager`对象被回收了；这种应该是异常状态

**Comment by hanouba** [comment]
> > > 清单文件中FileProvider 能将 android:authorities="${applicationId}" 修改为 android:authorities="${applicationId}.provider" 吗 或者自定义吗
> > 
> > 
> > 使用最新版本 是可以的
> 
> 我试过了 不行啊

我直接把这里修改成了这样android:authorities="${applicationId}.provider"
是修改方式不对吗

**Comment by azhon** [comment]
> > > 清单文件中FileProvider 能将 android:authorities="${applicationId}" 修改为 android:authorities="${applicationId}.provider" 吗 或者自定义吗
> > 
> > 
> > 使用最新版本 是可以的
> 
> 我试过了 不行啊

仔细检查代码，看稳定。DownloadManager有没有设置setAuthorities()

**Comment by azhon** [comment]
> > > 清单文件中FileProvider 能将 android:authorities="${applicationId}" 修改为 android:authorities="${applicationId}.provider" 吗 或者自定义吗
> > 
> > 
> > 使用最新版本 是可以的
> 
> 我试过了 不行啊

1.清单文件中设置FileProvider android:authorities="${applicationId}.provider" 
2.DownloadManager中设置setAuthorities("${applicationId}.provider")

**Comment by hanouba** [comment]
资源文件配置 会导致 cordova拍照功能无法调用

**Comment by hanouba** [comment]
不配置资源文件竟然也可以用

**Comment by azhon** [comment]
加我qq 细聊
