### ISSUE TITLE
程序已经有provider设置请问该怎么兼容

### ISSUE THREAD

**Issue by daijunsheng** [azhon/AppUpdate#31]
你好，我程序已经有

<provider
    android:name="android.support.v4.content.FileProvider"
    android:authorities="com.orange.fun.almost.FileProvider"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/rc_file_path"/>
</provider>
<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path
        name="rc_external_path"
        path="." />
    <root-path
        name="rc_root_path"
        path="" />
</paths>
请问这个和你要设置的该怎么兼容在一起，现在这个只能用其中一个
<--! android:authorities="${applicationId}" 
这个值必须与DownloadManager中的authorities一致（不设置则为应用包名）-->

<provider
    android:name="android.support.v4.content.FileProvider"
    android:authorities="${applicationId}"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/file_paths_public" />
</provider>
第四步：资源文件res/xml/file_paths_public.xml内容

<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path
        name="app_update_external"
        path="/" />
    <external-cache-path
        name="app_update_cache"
        path="/" />
</paths>

**Comment by daijunsheng** [comment]
你好，我程序已经有





<provider
    android:name="android.support.v4.content.FileProvider"
    android:authorities="com.orange.fun.almost.FileProvider"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/rc_file_path"/>
</provider>
<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path
        name="rc_external_path"
        path="." />
    <root-path
        name="rc_root_path"
        path="" />
</paths>
请问这个和你要设置的该怎么兼容在一起，现在这个只能用其中一个
<--! android:authorities="${applicationId}" 
这个值必须与DownloadManager中的authorities一致（不设置则为应用包名）-->

<provider
    android:name="android.support.v4.content.FileProvider"
    android:authorities="${applicationId}"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/file_paths_public" />
</provider>
第四步：资源文件res/xml/file_paths_public.xml内容

<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path
        name="app_update_external"
        path="/" />
    <external-cache-path
        name="app_update_cache"
        path="/" />
</paths>

**Comment by azhon** [comment]
使用最新版本2.0.0，可以支持自己设置authorities了`manager.setAuthorities()`
之前考虑不周
