### ISSUE TITLE
setAuthorities()问题

### ISSUE THREAD

**Issue by daijunsheng** [azhon/AppUpdate#32]
我现在用的就是最新版本的，android:authorities="com.orange.fun.almost.FileProvider"由于是这边设置的是这样，代码这是这样设置的setAuthorities(getActivity().getPackageName())是不是这里android:authorities="com.orange.fun.almost"改成包名就没问题了

**Comment by azhon** [comment]
看你Manifest中注册authorities是什么 setAuthorities("这里就填什么")
如：
android:authorities="com.orange.fun.almost.FileProvider"
setAuthorities("com.orange.fun.almost.FileProvider")
