### ISSUE TITLE
你好 我发现我更新到2.0.0后 没办法使用了 一直没找到那个库 AS使用implement导入的

### ISSUE THREAD

**Issue by JonsonBob** [azhon/AppUpdate#33]

**Comment by JonsonBob** [comment]
就是将版本从1.7.3 更新到2.0.0后 updateconfiguration 方法没办法 找到直接爆红

**Comment by azhon** [comment]
你是在你的项目依赖的还是依赖库依赖的？

**Comment by JonsonBob** [comment]
我的天 .... 这么快回复的么?  扯远了 .... 是项目依赖
![image](https://user-images.githubusercontent.com/30587007/51515968-95be3b80-1e50-11e9-82bd-34219b27f532.png)

**Comment by JonsonBob** [comment]
然后就这样了 
![image](https://user-images.githubusercontent.com/30587007/51516007-b7b7be00-1e50-11e9-84e3-e24050804c7c.png)

**Comment by JonsonBob** [comment]
我重启一下AS 就好了 ............. 现在还在懵逼这个问题是怎么解决的

**Comment by JonsonBob** [comment]
打扰了这么久 十分感谢 star
 已给
