### ISSUE TITLE
设置签名问题

### ISSUE THREAD

**Issue by zhangle1** [azhon/AppUpdate#40]
<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="com.bajiaoxing.intermediaryrenting.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths_public" />
        </provider>

            mManager.setApkName("appupdate"+TimeUtils.getCurrentTimeInLong()+".apk")
                    .setApkUrl(data.getFile())
                    .setAuthorities("com.bajiaoxing.intermediaryrenting.fileprovider")
我加了.fileprovider之后并修改authorities ，每次下载完之后都会提示三四部报错。 去掉又可以正常下载

**Comment by azhon** [comment]
xml 文件写对了没？

**Comment by zhangle1** [comment]
就是                .setAuthorities("com.bajiaoxing.intermediaryrenting.fileprovider")
 但是getAuthorities  依然是com.bajiaoxing.intermediaryrenting

**Comment by zhangle1** [comment]
我的问题 已解决
