### ISSUE TITLE
直接跳过下载进入安装界面

### ISSUE THREAD

**Issue by duolaimiha** [azhon/AppUpdate#42]
执行就跳转到安装界面。卸载删除安装包都没用。不知道为什么

**Comment by azhon** [comment]
不可能吧，跟踪代码看一下

**Comment by duolaimiha** [comment]
看了好久了，打断点看你内部代码都是执行到的。执行就跳转安装界面。换个手机或者下载地址又是正常的。不知道手机问题还是框架问题


------------------ 原始邮件 ------------------
发件人: "Code Porter"<notifications@github.com>;
发送时间: 2019年7月4日(星期四) 下午4:37
收件人: "azhon/AppUpdate"<AppUpdate@noreply.github.com>;
抄送: "........."<1057756963@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [azhon/AppUpdate] 直接跳过下载进入安装界面 (#42)




不可能吧，跟踪代码看一下

**Comment by duolaimiha** [comment]
肯定不是啊。网络都没有波动。有两个环境的，下载地址相同，一个环境安装包8M 一个54M。第一次是正常的下载了8M的 我切换到另一个环境。再次测试 更新 直接跳转安装了8M那个安装包了，正常应该下载54M的那个。然后就无限卡住了 卸载 删除apk都没用。 也可以加我qq给你看下现象1057756963


------------------ 原始邮件 ------------------
发件人: "Code Porter"<notifications@github.com>;
发送时间: 2019年7月4日(星期四) 下午4:42
收件人: "azhon/AppUpdate"<AppUpdate@noreply.github.com>;
抄送: "........."<1057756963@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [azhon/AppUpdate] 直接跳过下载进入安装界面 (#42)




那可以看下是不是一下载就成了
