### ISSUE TITLE
可不可以不用设置SmallIcon

### ISSUE THREAD

**Issue by xushengjiang0** [azhon/AppUpdate#43]
我是一名 ReactNative 开发人员，项目被我用到  rn 里面了。被我封装成Rn 的 android组件了，这里强制要求设置图标，可不可以自动读取主工程的图标。
另外setApkName可不可以自己设置成包名，也不用设置。

**Comment by azhon** [comment]
SmallIcon 对图标有要求的，需要自己设置，如果不显示通知栏进度条这个随便设张图片就行。
setApkName就是文件名，随你自己设置

**Comment by xushengjiang0** [comment]
好的谢谢
