### ISSUE TITLE
老铁咱自带的下载能否兼容 301、302重定向下载呢

### ISSUE THREAD

**Issue by ZQ173** [azhon/AppUpdate#45]
如题，该框架不错，希望能更完善下。

**Comment by azhon** [comment]
留下你的下载地址，我这边调下看下

**Comment by ZQ173** [comment]
http://qd.leaderhero.com/qd/androidapk/Stitcher-picstitcher-release-1.0.6.apk



------------------ 原始邮件 ------------------
发件人: "Code Porter"<notifications@github.com>; 
发送时间: 2019年7月12日(星期五) 中午1:08
收件人: "azhon/AppUpdate"<AppUpdate@noreply.github.com>; 
抄送: "ZQ"<173123831@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [azhon/AppUpdate] 老铁咱自带的下载能否兼容 301、302重定向下载呢 (#45)




留下你的下载地址，我这边调下看下

**Comment by azhon** [comment]
已经好了
