### ISSUE TITLE
安卓9如何实现通知栏

### ISSUE THREAD

**Issue by 748297973** [azhon/AppUpdate#46]
如何实现通知栏,我的p版本加上不显示

**Comment by azhon** [comment]
已经是支持的，自己检查下通知栏开关

**Comment by 748297973** [comment]
` UpdateConfiguration configuration = new UpdateConfiguration()
                //设置自定义的下载
                //.setHttpManager()
                //下载完成自动跳动安装页面
                .setJumpInstallPage(true)
                //设置对话框背景图片 (图片规范参照demo中的示例图)
                //.setDialogImage(R.drawable.ic_dialog)
                //设置按钮的颜色
                //.setDialogButtonColor(Color.parseColor("#E743DA"))
                //设置按钮的文字颜色
                .setDialogButtonTextColor(Color.WHITE)
                //支持断点下载
                .setBreakpointDownload(true)
                //设置是否显示通知栏进度
                .setShowNotification(true)
                .setNotifyId(100)
                //设置是否提示后台下载toast
                .setShowBgdToast(false)
                //设置强制更新
                .setForcedUpgrade(isForce)
                //设置对话框按钮的点击监听
                .setButtonClickListener(this)
                //设置下载过程的监听
                .setOnDownloadListener(this);

        manager = DownloadManager.getInstance(this);
        manager.setApkName("K8Movie.apk")
                .setApkUrl(appUrl)
                .setSmallIcon(R.mipmap.ic_launcher)
                .setShowNewerToast(true)
                .setConfiguration(configuration)
                .setDownloadPath(Environment.getExternalStorageDirectory() + "/K8Movie")
                .setApkVersionName(appVersion)
                .setApkVersionCode(appVersionCode)
//                .setApkSize("20.4")
                .setAuthorities(getPackageName())
                .setApkDescription(appNote)
                .download();`

**Comment by 748297973** [comment]
`  @Override
    public void start() {
        NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(this);
        NotificationUtil.showNotification(this,R.mipmap.ic_launcher_round,"开始下载","下载中");

    }

    @Override
    public void downloading(int max, int progress) {
        NotificationUtil.showProgressNotification(this,R.mipmap.ic_launcher_round,"下载中","下载",max,progress);    }`

**Comment by 748297973** [comment]
哪里有问题

**Comment by azhon** [comment]
系统的通知栏开关设置.......
