### ISSUE TITLE
可以动态切换下载Url吗

### ISSUE THREAD

**Issue by c4jeff** [azhon/AppUpdate#50]
有多个下载Url，Apk因为部分Url错误或者url被墙导致下载出错，需要切换其他可用Url地址
现在测试重新调用setApkUrl(newUul).download();无响应

**Comment by azhon** [comment]
自己监听下载失败，在开启下载------------------ 原始邮件 ------------------
发件人: "Jeff Lin"<notifications@github.com>
发送时间: 2019年8月14日(星期三) 下午5:57
收件人: "azhon/AppUpdate"<AppUpdate@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [azhon/AppUpdate] 可以动态切换下载Url吗 (#50)



有多个下载Url，Apk因为部分Url错误或者url被墙导致下载出错，需要切换其他可用Url地址
 现在测试重新调用setApkUrl(newUul).download();无响应
 
&mdash;

**Comment by c4jeff** [comment]
失败后重新调用DownloadManager.download(); 
会进到DownloadManager.java的317行//对版本进行判断，是否显示升级对话框
UpdateDialog dialog = new UpdateDialog(context); dialog.show();
不会重启DownloadService.class
![捕获](https://user-images.githubusercontent.com/22916370/63070625-7e5eb100-bf4e-11e9-864c-79ca21daf96c.PNG)
此时的对话框依然存在，显示正在下载

**Comment by azhon** [comment]
你就不要设置versionCode进去，自己写个升级对话框



------------------ 原始邮件 ------------------
发件人: "Jeff Lin"<notifications@github.com>; 
发送时间: 2019年8月15日(星期四) 中午11:21
收件人: "azhon/AppUpdate"<AppUpdate@noreply.github.com>; 
抄送: "阿钟"<958460248@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [azhon/AppUpdate] 可以动态切换下载Url吗 (#50)




失败后重新调用DownloadManager.download();
 会进到DownloadManager.java的317行//对版本进行判断，是否显示升级对话框
 UpdateDialog dialog = new UpdateDialog(context); dialog.show();
 不会重启DownloadService.class
 
 此时的对话框依然存在，显示正在下载

**Comment by c4jeff** [comment]
嗯，现在的做法是自己实现升级对话框，3Q
