### ISSUE TITLE
大佬，报这个错，咋整

### ISSUE THREAD

**Issue by shiwukuanghun** [azhon/AppUpdate#51]
java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Ljava/lang/String;)V in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in /data/app/m.hongle-eb4iQYSondALfZoq2Pqoxg==/base.apk!classes14.dex)

**Comment by azhon** [comment]
你这是没有找到NotificationCompat类，对着demo查看依赖v4包的版本
