### ISSUE TITLE
下载速度好慢啊，我的apk才18M不到，要下好几分钟，但是我放把下载链接放浏览器几秒就下完了

### ISSUE THREAD

**Issue by shiwukuanghun** [azhon/AppUpdate#52]
大佬，这是什么原因造成的

**Comment by shiwukuanghun** [comment]
首先我可以100%排除网络原因，因为同样的情况我在浏览器试了好多遍

**Comment by azhon** [comment]
你试试不断点下载要多久，下载慢是因为文件随机写入慢，最新的版本已经加了缓冲


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: shiwukuanghun <notifications@github.com>
发送时间: 2019年8月14日 23:32
收件人: azhon/AppUpdate <AppUpdate@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[azhon/AppUpdate] 下载速度好慢啊，我的apk才18M不到，要下好几分钟，但是我放把下载链接放浏览器几秒就下完了 (#52)
