### ISSUE TITLE
部分机型报错

### ISSUE THREAD

**Issue by yushilong** [azhon/AppUpdate#54]
android.os.FileUriExposedException: file:///storage/emulated/0/.sh/update/download exposed beyond app through Intent.getData()
    at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
    at android.net.Uri.checkFileUriExposed(Uri.java:2356)
    at android.content.Intent.prepareToLeaveProcess(Intent.java:10523)
    at android.content.Intent.prepareToLeaveProcess(Intent.java:10477)
    at android.app.PendingIntent.getActivity(PendingIntent.java:345)
    at android.app.PendingIntent.getActivity(PendingIntent.java:307)
    at cn.shihuo.modulelib.views.service.UpdateService.e(UpdateService.java:298)
    at cn.shihuo.modulelib.views.service.UpdateService.a(UpdateService.java:35)
    at cn.shihuo.modulelib.views.service.UpdateService$b.a(UpdateService.java:457)
    at cn.shihuo.modulelib.views.service.UpdateService$b.onPostExecute(UpdateService.java:330)

<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths_public" />
        </provider>

<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path
            name="app_update_external"
            path="/" />
    <external-cache-path
            name="app_update_cache"
            path="/" />
</paths>

**Comment by azhon** [comment]
有没有正确配置fileprovider。下载文件存放路径

**Comment by yushilong** [comment]
> 有没有正确配置fileprovider。下载文件存放路径

部分机型哎，我看项目里面是配置了的

`<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths_public" />
        </provider>`

**Comment by yushilong** [comment]
> 有没有正确配置fileprovider。下载文件存放路径

`<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path
            name="app_update_external"
            path="/" />
    <external-cache-path
            name="app_update_cache"
            path="/" />
</paths>`

**Comment by azhon** [comment]
mainfest呢？自己在从头看下文档

**Comment by yushilong** [comment]
> mainfest呢？自己在从头看下文档

`<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths_public" />
        </provider>

<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path
            name="app_update_external"
            path="/" />
    <external-cache-path
            name="app_update_cache"
            path="/" />
</paths>`

**Comment by yushilong** [comment]
> mainfest呢？自己在从头看下文档

<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths_public" />
        </provider>

<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path
            name="app_update_external"
            path="/" />
    <external-cache-path
            name="app_update_cache"
            path="/" />
</paths>

**Comment by yushilong** [comment]
<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths_public" />
        </provider>

<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path
            name="app_update_external"
            path="/" />
    <external-cache-path
            name="app_update_cache"
            path="/" />
</paths>

**Comment by yushilong** [comment]
怎么复制不了代码了

**Comment by yushilong** [comment]
![image](https://user-images.githubusercontent.com/5087094/63336189-4c47b780-c371-11e9-8876-42a1be7714c7.png)
![image](https://user-images.githubusercontent.com/5087094/63336206-549ff280-c371-11e9-8808-52cfb1972bd4.png)

**Comment by azhon** [comment]
调用的代码呢

**Comment by yushilong** [comment]
> 调用的代码呢

![image](https://user-images.githubusercontent.com/5087094/63336355-9fba0580-c371-11e9-9691-e98ce9994023.png)

**Comment by azhon** [comment]
debug查查下载成功那部分代码调用看看

**Comment by yushilong** [comment]
好吧，这个是友盟收集到的
