### ISSUE TITLE
强制更新的bug

### ISSUE THREAD

**Issue by lodgkk** [azhon/AppUpdate#56]
如果我是强制更新,当下载完,跳转到安装页面,我点取消,返回app,自带的dialog还在界面上,去掉不了

**Comment by azhon** [comment]
这种情况应该怎么处理好一些？征求一下意见。

**Comment by lodgkk** [comment]
如果需求里面确定不能取消dialog的话,那就当下载完成后,按钮变成立即安装,这样他跳转安装,取消安装回来的时候,按钮也可以再次点击跳转安装

**Comment by lodgkk** [comment]
然后设置,再次点击退出页面

**Comment by azhon** [comment]
v2.4.0已经解决，感谢支持！
