### ISSUE TITLE
AppUpdate正在征集框架使用者信息，希望得到大家的支持！🙏🙏🙏

### ISSUE THREAD

**Issue by azhon** [azhon/AppUpdate#58]
####  　　到目前为止在[JFrog Bintray](https://bintray.com/beta/#/azhon/azhon/appupdate?tab=statistics)总下载量已经突破`30k+`(截止到2020年4月16日)👏👏👏，为了增强那些还在犹豫不决该使用哪个库的开发者信心；现向大家征集框架使用者信息，希望得到大家的支持🙏格式如下：

- [x] 应用名称：
- [x] 公司官网/应用下载地址/应用商店地址：

#### JFrog Bintray全球下载量分布图
![1](https://user-images.githubusercontent.com/20559556/64326665-f4f64800-cffc-11e9-9bf3-b5964e13cf7a.png)

**Comment by lodgkk** [comment]
易果无忧
外包项目

**Comment by azhon** [comment]
第二行填App下载地址呀，不是项目类型




------------------ 原始邮件 ------------------
发件人: "lodgkk"<notifications@github.com>; 
发送时间: 2019年9月5日(星期四) 上午8:32
收件人: "azhon/AppUpdate"<AppUpdate@noreply.github.com>; 
抄送: "阿钟"<958460248@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [azhon/AppUpdate] AppUpdate正在征集框架使用者信息，希望得到大家的支持！&#x1F64F;&#x1F64F;&#x1F64F; (#58)




易果无忧
 外包项目

**Comment by dingpengqiang** [comment]
提供可以更改进度条的展示位置

**Comment by dingpengqiang** [comment]
小米手机要设置高权限的通知，负责不显示

**Comment by lydlovexyz** [comment]
慧健康和慧健康医生版
华为 小米 OPPO vivo 360应用市场

**Comment by akingyin1987** [comment]
非强制升级能不能显示进度对话框

**Comment by jiapengtao** [comment]
应用名称：后乐光伏监控
下载地址：360应用市场

**Comment by akingyin1987** [comment]
在android9.0+ 没有下载提示音

**Comment by callhh** [comment]
应用名称：虾米生活
下载地址:应用宝 华为 小米 OPPO vivo 360等应用市场

**Comment by taoczZYC** [comment]
爱多路
https://a.app.qq.com/o/simple.jsp?pkgname=com.hitotech.idoru

**Comment by ckl006y** [comment]
谢谢

**Comment by kw543178** [comment]
这个项目能增加个支持除当前应用外的其他应用的更新下载功能吗？

**Comment by azhon** [comment]
现在的不就可以吗？
