### ISSUE TITLE
强制更新的时候 可不可以加上点击返回键 退出APP的功能

### ISSUE THREAD

**Issue by hexin9456** [azhon/AppUpdate#61]
强制更新的时候 可不可以加上点击返回键 退出APP的功能   如果没有的话 用户不想升级 想退出的时候 就退不出去了

**Comment by azhon** [comment]
使用切后台任务键就可以了

**Comment by hexin9456** [comment]
Home键吗  但是一般用户都会使用 返回键 去退出应用。Home键也是一种办法

**Comment by azhon** [comment]
强制更新本来就是让用户必须去更新才能使用，你让他可以随便退出；这不是在少流量吗

**Comment by hexin9456** [comment]
测试提出的问题，只有这么回他了

**Comment by azhon** [comment]
好吧，如果必须要改你就自己写个对话框

**Comment by hexin9456** [comment]
好的 谢谢 大佬回复！
