### ISSUE TITLE
应用退到后台无法弹出安装器

### ISSUE THREAD

**Issue by CaiJingFu** [azhon/AppUpdate#64]
应用只有在前台时才能显示出安装器，退到后台就无法显示出安装器了。

**Comment by CaiJingFu** [comment]
测试机是小米8SE， Android 版本9.0 10.0和模拟器Android 版本9.0 10.0都不行

**Comment by azhon** [comment]
我这边使用Android P、Q模拟器退出到后台是可以打开安装器的。
你看下是不是小米系统做了限制

**Comment by CaiJingFu** [comment]
我的模拟器是pixel 2，API是29，Android版本是10.0(Google Play)和pixel XL，API是28，Android版本是9.0(Google Play)，退到后台还是无法安装。还是我下载下来的demo不是最新的？

**Comment by azhon** [comment]
那你下载源码运行来测试一下，我这边测试用的也是API 28 29



------------------ 原始邮件 ------------------
发件人: "CaiJingFu"<notifications@github.com>; 
发送时间: 2019年11月4日(星期一) 中午12:11
收件人: "azhon/AppUpdate"<AppUpdate@noreply.github.com>; 
抄送: "阿钟"<958460248@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [azhon/AppUpdate] 应用退到后台无法弹出安装器 (#64)




我的模拟器是pixel 2，API是29，Android版本是10.0(Google Play)和pixel XL，API是28，Android版本是9.0(Google Play)，退到后台还是无法安装。还是我下载下来的demo不是最新的？

**Comment by CaiJingFu** [comment]
不好意思 我在公司的时候运行的是你老的版本的 所以没有弹出来 现在这个新版本的可以了 模拟器，小米8SE都是可以弹出来的

**Comment by azhon** [comment]
那就行



------------------ 原始邮件 ------------------
发件人: "CaiJingFu"<notifications@github.com>; 
发送时间: 2019年11月4日(星期一) 下午3:24
收件人: "azhon/AppUpdate"<AppUpdate@noreply.github.com>; 
抄送: "阿钟"<958460248@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [azhon/AppUpdate] 应用退到后台无法弹出安装器 (#64)




不好意思 我在公司的时候运行的是你老的版本的 所以没有弹出来 现在这个新版本的可以了 模拟器，小米8SE都是可以弹出来的
