### ISSUE TITLE
下载过程中突然断网，能监听这种状态码， 看了目前的OnDownloadListener好像没有监听这种情况

### ISSUE THREAD

**Issue by zhangshaobo87** [azhon/AppUpdate#66]

**Comment by azhon** [comment]
这种情况会走回调的error()吧

**Comment by zhangshaobo87** [comment]
sorry 好像是我的问题，是不是每次只能在一个地方监听到，我在activity里边弹出了一个dialog，在dialog和activity同时监听，然后dialog中能监听到，activity中监听不到。

**Comment by azhon** [comment]
你可以使用下最新的2.5.0版本，支持添加多个监听器

**Comment by zhangshaobo87** [comment]
我现在用的就是2.5.0呀
`UpdateConfiguration configuration = new UpdateConfiguration()
                    .setJumpInstallPage(true)
                    .setShowBgdToast(true)
                    .setOnDownloadListener(this);`

这种方式监听的

**Comment by zhangshaobo87** [comment]
那我再试下

**Comment by azhon** [comment]
你可以加下qq群：828385813便于交流
