### ISSUE TITLE
android6.0

### ISSUE THREAD

**Issue by songsongtao** [azhon/AppUpdate#69]
在用户的android6的手机上会解析安装包失败无法安装，7.0,8.0等都正常

**Comment by songsongtao** [comment]
自己拿小米6.0的测试了也是一样，希望作者解决

**Comment by songsongtao** [comment]
.setDownloadPath(context.getCacheDir().getAbsolutePath() + "/AppUpdate")
设置下载地址的原因，导致6.0的问题，但是还是不能理解

**Comment by azhon** [comment]
6.0是可以设置外部存储地址的，解析失败你看下是包有问题，还是拉起安装的时候有问题

**Comment by songsongtao** [comment]
我设置的是内部存储导致的问题，使用默认地址正常，只有6.0会这样

**Comment by azhon** [comment]
那可以看下logcat的日志，你可以加下qq群方便讨论
