### ISSUE TITLE
为什么我在manifest中设置了票provider 还是提示Couldn't find meta-data for provider with authority

### ISSUE THREAD

**Issue by zhangshaobo87** [azhon/AppUpdate#74]
是哪里不对吗
![image](https://user-images.githubusercontent.com/17812840/71649389-57f8b100-2d49-11ea-9329-cef18d3974ea.png)
![image](https://user-images.githubusercontent.com/17812840/71649396-61821900-2d49-11ea-86c4-ec4056753f12.png)
 这些都配置了呀

**Comment by azhon** [comment]
你点击manifest底部的合并视图看下 里面有没有。
![QQ截图20200102102254](https://user-images.githubusercontent.com/20559556/71649470-069cf180-2d4a-11ea-85fa-f33249dfa12d.png)

**Comment by zhangshaobo87** [comment]
有
![image](https://user-images.githubusercontent.com/17812840/71649578-f76a7380-2d4a-11ea-8ac0-13241323b8c3.png)

**Comment by azhon** [comment]
加群828385813给你看下

**Comment by zhangshaobo87** [comment]
加了
