### ISSUE TITLE
楼主，建个技术交流群吧，框架挺好用，希望可以更加自由的自定义界面

### ISSUE THREAD

**Issue by jiapengtao** [azhon/AppUpdate#76]
**Bug标题**
清楚简明的描述你遇到的问题

**AppUpdate参数设置**
截图`DownloadManager`配置

**复现步骤**
1. 点击下载
2. ......

**错误Logcat日志截图**
日志截图

**软件版本信息**
 - Android Studio：[eg：3.6]
 - AppUpdate：[eg：2.6.0]
 - 设备品牌：[eg：Google]
 - 设备型号：[eg：Pixel 2]
 - 设备系统版本：[eg：9.0]

**额外有用的信息**
补充额外有用的信息

**Comment by azhon** [comment]
群已经有了，一看你就是没有看README。。。。界面完全都是可以自己随便写的，你可以参考Demo
