### ISSUE TITLE
https下可能会出现证书问题

### ISSUE THREAD

**Issue by brmnh666** [azhon/AppUpdate#77]
**Bug标题**
https下可能会出现证书问题

**AppUpdate参数设置**
截图`DownloadManager`配置

**复现步骤**
1. 点击下载

**错误Logcat日志截图**
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**软件版本信息**
 - Android Studio：[eg：3.6]
 - AppUpdate：[eg：2.6.0]
 - 设备品牌：[eg：Google]
 - 设备型号：[eg：Pixel 2]
 - 设备系统版本：[eg：9.0]

**额外有用的信息**
补充额外有用的信息

**Comment by azhon** [comment]
你这是自己解决了吗
