### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by luxiaochuang** [azhon/AppUpdate#78]
**Bug标题**
安装apk FileProvider 报错 并且导致 腾讯广告 安装

**AppUpdate参数设置**
 DownloadManager manager = DownloadManager.getInstance(context);
                            manager.setApkName(context.getString(R.string.app_name)+".apk")
                                    .setApkUrl(data.getUrl())
                                    .setSmallIcon(R.mipmap.ic_launcher)
                                    .setShowNewerToast(true)
                                    .setConfiguration(configuration)
                                    .setApkVersionCode(Integer.MAX_VALUE)
                                    .setApkVersionName(data.getVersion_name())
                                    .setApkSize("12.5")
                                   // .setAuthorities("cao.huasheng.juhaokan.fileProvider")
                                    .setApkDescription(data.getContent())
//                                    .setApkMD5("DC501F04BBAA458C9DC33008EFED5E7F")
                                    .download();

**复现步骤**
1. 点击下载
2. ......

**错误Logcat日志截图**
日志截图

**软件版本信息**
 - Android Studio：[eg：3.6]
 - AppUpdate：[eg：2.6.0]
 - 设备品牌：[eg：Google]
 - 设备型号：[eg：Pixel 2]
 - 设备系统版本：[eg：9.0]

**额外有用的信息**
补充额外有用的信息

**Comment by azhon** [comment]
你使用最新2.8.0版本就好了，集成吧步骤看文档
