### ISSUE TITLE
小建议，希望通知栏的标题能够开放出来自定义。

### ISSUE THREAD

**Issue by ZQ173** [azhon/AppUpdate#79]
如题，希望自定义能更灵活一些，3Q。

**Comment by azhon** [comment]
这个已经是支持的，你在string.xml定义个同名的字符串就可以替换掉框架的标题了
<img width="793" alt="image" src="https://user-images.githubusercontent.com/20559556/75685812-29aa3a00-5cd6-11ea-87a3-800edcaecfb5.png">
