### ISSUE TITLE
目录结构相同导致无法运行问题

### ISSUE THREAD

**Issue by songsongtao** [azhon/AppUpdate#83]
**Bug标题**
INSTALL_FAILED_CONFLICTING_PROVIDER，无法安装

**AppUpdate参数设置**
截图`DownloadManager`配置
'com.azhon:appupdate:2.8.0'
**复现步骤**
有两个相同目录的的项目复制过去的，applicationId不同包结构相同

**错误Logcat日志截图**
INSTALL_FAILED_CONFLICTING_PROVIDER

**额外有用的信息**
2.8的Authorities是自动生成的，会根据当前包名目录获取，复制的项目会报错

**Comment by azhon** [comment]
你肯定漏看了集成文档第二步

**Comment by songsongtao** [comment]
我的锅

**Comment by azhon** [comment]
最近会发布2.9.0版本，将第二步也省略
