### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by keybalabala** [azhon/AppUpdate#84]
希望能提供api可以使用自定义的UI模板

**Comment by azhon** [comment]
比如说？
如果是对话框的话是已经提供了的，如果不符合那么就需要你自己写一个对话框
如果是通知栏的文字显示，你只需要在string.xml取相同名字便可修改

**Comment by keybalabala** [comment]
我指的是UpdateDialog，不符合的话需要重写dialog逻辑，如果能提供个api，传入layout并在layoutview中规定需要设置的id（文档说明）会不会更好一点

**Comment by azhon** [comment]
那感觉太复杂了，影响代码；这种情况直接Ctrl C V拷贝默认的对话框然后自己改内容
