### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by yishangfei** [azhon/AppUpdate#85]
**Bug标题**
清楚简明的描述你遇到的问题
写在onstart 或者onresume里面
回到桌面然后回去button会变成升级 要再点升级才会恢复 
这个有什么好的解决办法吗

**AppUpdate参数设置**
截图`DownloadManager`配置

**复现步骤**

**错误Logcat日志截图**
日志截图

**软件版本信息**
 - Android Studio：
 - AppUpdate：
 - 设备品牌：
 - 设备型号：
 - 设备系统版本：

**额外有用的信息**
补充额外有用的信息

**Comment by azhon** [comment]
没看懂你的问题，你进下QQ群，然后录个视频看下
