### ISSUE TITLE
最新版本2.9.0,android10后台下载完成后,显示下载出错,无论点击多少次重新下载都是一样

### ISSUE THREAD

**Issue by lodgkk** [azhon/AppUpdate#87]
**Bug标题**
最新版本2.9.0,android10后台下载完成后,显示下载出错,无论点击多少次重新下载都是一样

**额外有用的信息**
5.0的机子可以正常,还有2.8.0没有问题

**Comment by azhon** [comment]
那你查看下日志

**Comment by lodgkk** [comment]
因为是通知栏那里的,我看看能不能看把

**Comment by azhon** [comment]
![image](https://user-images.githubusercontent.com/20559556/80076618-0a65b580-857f-11ea-99bc-e9d0f6897b92.png)

**Comment by lodgkk** [comment]
文件已下载至/storage/emulated/0/Android/data/com.highzou.country/cache/higo_country_version5.apk
2020-04-24 10:40:44.929 9863-10405/com.highzou.country E/AppUpdate.DownloadService: error: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Android/data/com.highzou.country/cache/higo_country_version5.apk

**Comment by lodgkk** [comment]
/*
         * 整个库允许配置的内容
         * 非必选
         */
        UpdateConfiguration configuration = new UpdateConfiguration()
                //输出错误日志
                .setEnableLog(true)
                //设置自定义的下载
                //.setHttpManager()
                //下载完成自动跳动安装页面
                .setJumpInstallPage(true)
                //设置对话框背景图片 (图片规范参照demo中的示例图)
                //.setDialogImage(R.drawable.ic_dialog)
                //设置按钮的颜色
                //.setDialogButtonColor(Color.parseColor("#E743DA"))
                //设置对话框强制更新时进度条和文字的颜色
                //.setDialogProgressBarColor(Color.parseColor("#E743DA"))
                //设置按钮的文字颜色
                .setDialogButtonTextColor(Color.WHITE)
                //设置是否显示通知栏进度
                .setShowNotification(true)
                //设置是否提示后台下载toast
                .setShowBgdToast(true)
                //设置强制更新
                .setForcedUpgrade(false)
                //设置对话框按钮的点击监听
                .setButtonClickListener(this)
                //设置下载过程的监听
                .setOnDownloadListener(this);

        manager = DownloadManager.getInstance(this);
        manager.setApkName("higo_country_version" + version + ".apk")
                .setApkUrl(url)
                .setSmallIcon(R.mipmap.ic_launcher)
                .setShowNewerToast(true)
                .setConfiguration(configuration)
                .setApkVersionCode(verCode)
                .setApkVersionName(version)
                .setApkDescription(note)
//                .setApkMD5("DC501F04BBAA458C9DC33008EFED5E7F")
                .download();

**Comment by azhon** [comment]
你这个错看着有点怪，你跑下demo看有没有用

**Comment by lodgkk** [comment]
应该是找不到文件

**Comment by azhon** [comment]
你进下qq群，不是存储路径改动问题

**Comment by lodgkk** [comment]
github打开图片有时候很难打开,我连续几天都看不到图片了,qq群的号码是多少呢

**Comment by azhon** [comment]
828385813
