### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by WinWang** [azhon/AppUpdate#9]
如果是强制升级的话，用默认的dialog的话，楼主的升级按钮设置成了灰色，这样会给人一种不能点击的错觉，建议还是设置成橘黄色好点
![2345 20180507180041](https://user-images.githubusercontent.com/19348069/39696720-233f5f90-5221-11e8-8cee-b548cd64607a.png)

**Comment by azhon** [comment]
我没有将按钮设置成灰色，你依赖最新版本看下.

**Comment by WinWang** [comment]
我依赖的是最新的1.5.1版本的，我看了下demo确实是橙色的，我看楼主是通过主题指定的颜色，能不能通过设置背景来指定颜色呢？我可能项目依赖了QMUI导致主题的颜色失效的

**Comment by azhon** [comment]
那你可能要直接依赖module 你自己改了

**Comment by WinWang** [comment]
搞定了，我在自己的主题重新指定一次theme的颜色
