### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by TianTingting** [azhon/AppUpdate#90]
**Bug标题**
锁屏状态下下载完成，通知栏下载进度条消失，进入app界面，没有自动安装提示

**AppUpdate参数设置**
截图`DownloadManager`配置
![image](https://user-images.githubusercontent.com/19221117/83857987-5e52e500-a74e-11ea-9cee-e7277d499826.png)
**复现步骤**

**错误Logcat日志截图**
日志截图

**软件版本信息**
 - Android Studio：最新版本
 - AppUpdate：2.9.0
 - 设备品牌：oppo R17
 - 设备型号：pbemoo
 - 设备系统版本：10.0
**额外有用的信息**
补充额外有用的信息

**Comment by azhon** [comment]
![image](https://user-images.githubusercontent.com/20559556/83858259-cdc8d480-a74e-11ea-89be-17db3aba1f84.png)

**Comment by TianTingting** [comment]
我没太懂这句话的意思？需要申请权限什么的吗？

**Comment by azhon** [comment]
就是Android10不允许后台启动页面
https://developer.android.google.cn/guide/components/activities/background-starts

**Comment by TianTingting** [comment]
这个具体没有办法改是吗？能不能有具体实现步骤！

**Comment by azhon** [comment]
这是Android系统的限制啊！！！！！！

**Comment by TianTingting** [comment]
那这个下载完成以后，点击更新，能判断是否下载完成然后直接调用系统安装操作？

**Comment by azhon** [comment]
下载完成后，对话框会显示成点击安装

**Comment by TianTingting** [comment]
用的是自己的弹窗，没有用内置的！

**Comment by azhon** [comment]
那你就自己参照内置对话框代码去实现
