### ISSUE TITLE
bugly上传bug

### ISSUE THREAD

**Issue by GXSZone** [azhon/AppUpdate#92]
#33702 java.lang.NullPointerException

系统版本

Android 8.0.0,level 26

ROM

HuaWei/EMOTION

设备机型

华为 BAC TL00

CPU架构

arm64-v8a

```
Attempt to invoke virtual method 'java.lang.String java.io.File.getPath()' on a null object reference
com.azhon.appupdate.manager.DownloadManager.boolean checkParams()(DownloadManager.java:7)
```

**Comment by azhon** [comment]
看起来怪怪的，是不是使用的不当

**Comment by GXSZone** [comment]
应该是当的，就那几个设置

**Comment by azhon** [comment]
那就奇怪, DownloadManager 类中都没有用到File类

**Comment by muxiaozi** [comment]
貌似是 [context.getExternalCacheDir().getPath()](https://github.com/azhon/AppUpdate/blob/master/appupdateX/src/main/java/com/azhon/appupdate/manager/DownloadManager.java#L375) 出问题
怀疑没有读写存储权限导致

**Comment by azhon** [comment]
> 貌似是 [context.getExternalCacheDir().getPath()](https://github.com/azhon/AppUpdate/blob/master/appupdateX/src/main/java/com/azhon/appupdate/manager/DownloadManager.java#L375) 出问题
> 怀疑没有读写存储权限导致

这个获取不需要存储权限

**Comment by muxiaozi** [comment]
你说的对，那就是因为外部存储不可用，最好这么判断一下 [安卓API](https://developer.android.com/reference/android/content/Context#getExternalCacheDir())
```java
/**
  * 获取app缓存路径
  * @param context
  * @return
  */
 public String getCachePath( Context context ){
     String cachePath ;
     if (Environment.MEDIA_MOUNTED.equals(Environment.getExternalStorageState())
             || !Environment.isExternalStorageRemovable()) {
         //外部存储可用
         cachePath = context.getExternalCacheDir().getPath() ;
     }else {
         //外部存储不可用
         cachePath = context.getCacheDir().getPath() ;
     }
     return cachePath ;
 }
```
