### ISSUE TITLE
java.net.ProtocolException: unexpected end of stream

### ISSUE THREAD

**Issue by HurryCong** [azhon/AppUpdate#93]
华为荣耀8X  使用库中默认的下载管理方式报错
库版本：2.9.0
<img width="558" alt="微信截图_20200619175946" src="https://user-images.githubusercontent.com/16949907/85217924-e7615180-b3c7-11ea-8c18-4ce41a5eadb5.png">

**Comment by azhon** [comment]
百度搜搜，应该是你的下载地址有问题
